language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker run -t  --entrypoint="/bin/sh" -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6 -c "zef install Slang::Tuxic && perl6 -I. -Ilib t/81_subclass.t || true"

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test -e ZEF_SUBMIT_TESTREPORTS=1  jjmerelo/test-perl6

after_success:
    -  docker run -t  --entrypoint="/bin/sh" -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6 -c "zef list --installed --verbose"

notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
