language: perl
perl:
    - "5.20"
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-master/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/zef/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
    - rakudobrew build-zef
    - zef install Slang::Tuxic File::Temp
install:
    - export PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-master/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/zef/bin:$PATH
    - zef install --depsonly .        || true
before_script:
    - zef --installed --verbose list  || true
    - perl6 -I. -Ilib t/81_subclass.t || true
script:
    - prove -v -e 'perl6 -Ilib' t
    - ZEF_SUBMIT_TESTREPORTS=1 zef install .
after_success:
    - zef list --installed --verbose
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
